int _putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _isLower(int c);
int _isAlpha(int n);
int _abc(int);
int print_last_digit(int);
void jack_bauer(void);
void times_table(void);
int add(int, int);
void print_to_98(int n);
void print_times_table(int n);
